### ISSUE TITLE
SSH/TELNET

### ISSUE THREAD

**Issue by The-Memzer** [l4tt/cnc-finder#2]
SSH/TELNET brute??? With mysql I didn't really find anything :/, do you know anything I could use mysql for??? I only found a ransomware note. With SSH/TELNET access, you can control the botnet. This isn't a bug, just a request for a better botnet finder.

**Comment by l4tt** [comment]
mainly, this goes off of urlcaus index, and try's to identify if it's part of a botnet
since IP's have been reported to there index for abuse. subject of the matter is that unless there is a better index there is no possible way to find more target's, for abuse purposes
